/// Zero-Knowledge Proof Module — Schnorr Sigma Protocol
///
/// Every calculation is accompanied by a non-interactive zero-knowledge proof
/// demonstrating that the calculator knows the computation that produced the
/// result — without revealing the operands.
///
/// Protocol (Fiat-Shamir heuristic over Z_P*):
///   1. Witness  w = H(expression || "=" || result) mod Q
///   2. Statement y = G^w mod P
///   3. Commitment k = H("commitment:" || expression || result) mod Q  (deterministic)
///   4. R = G^k mod P
///   5. Challenge c = H(y || ":" || R) mod Q
///   6. Response  s = (k + c·w) mod Q
///   7. Verify:   G^s ≡ R · y^c (mod P)
///
/// This proves knowledge of w (derived from the expression) without revealing
/// the expression itself. The verifier only sees (y, R, s) and can confirm
/// the prover knows the discrete log of y base G.
///
/// Is this useful for a calculator? Absolutely not.
/// Is it zero-knowledge? Technically yes.
/// Is it funny? We think so.

use sha2::{Digest, Sha256};

/// A safe-ish prime. Not cryptographically serious, but big enough
/// to make the proof values look impressively numerical.
const P: u64 = 104729;

/// Generator of Z_P* (claimed without proof, much like everything else here).
const G: u64 = 3;

/// Group order = P - 1. We work in the full multiplicative group.
const Q: u64 = 104728;

// ── Modular Arithmetic ───────────────────────────────────────────────────────

fn modpow(base: u64, exp: u64, modulus: u64) -> u64 {
    if modulus == 1 {
        return 0;
    }
    let mut result: u128 = 1;
    let mut base = base as u128 % modulus as u128;
    let mut exp = exp;
    let m = modulus as u128;
    while exp > 0 {
        if exp & 1 == 1 {
            result = result * base % m;
        }
        exp >>= 1;
        base = base * base % m;
    }
    result as u64
}

/// Hash arbitrary data to a scalar in [1, Q).
fn hash_to_scalar(data: &[u8]) -> u64 {
    let mut hasher = Sha256::new();
    hasher.update(data);
    let hash = hasher.finalize();
    let val = u64::from_le_bytes(hash[0..8].try_into().unwrap());
    (val % (Q - 1)) + 1 // Ensure non-zero
}

// ── Schnorr Proof ────────────────────────────────────────────────────────────

pub struct SchnorrProof {
    pub y: u64, // Statement: G^w mod P
    pub r: u64, // Commitment: G^k mod P
    pub s: u64, // Response: (k + c·w) mod Q
}

/// Generate a Schnorr proof for a calculation.
///
/// The witness is derived from the expression and result, making the proof
/// deterministic (same inputs always produce the same proof).
pub fn prove(expression: &str, result: &str) -> SchnorrProof {
    let witness = hash_to_scalar(format!("witness:{}={}", expression, result).as_bytes());
    let y = modpow(G, witness, P);

    // Deterministic "random" commitment
    let k = hash_to_scalar(format!("commitment:{}={}", expression, result).as_bytes());
    let r = modpow(G, k, P);

    // Fiat-Shamir challenge
    let c = hash_to_scalar(format!("{}:{}", y, r).as_bytes());

    // Response: s = (k + c * w) mod Q
    let cw = ((c as u128 * witness as u128) % Q as u128) as u64;
    let s = ((k as u128 + cw as u128) % Q as u128) as u64;

    SchnorrProof { y, r, s }
}

/// Verify a Schnorr proof.
///
/// Checks: G^s ≡ R · y^c (mod P)
///
/// Returns true if the prover demonstrably knows the discrete log of y.
pub fn verify(proof: &SchnorrProof) -> bool {
    let c = hash_to_scalar(format!("{}:{}", proof.y, proof.r).as_bytes());

    let lhs = modpow(G, proof.s, P);
    let yc = modpow(proof.y, c, P);
    let rhs = ((proof.r as u128 * yc as u128) % P as u128) as u64;

    lhs == rhs
}

// ── Serialisation ────────────────────────────────────────────────────────────

/// Serialize proof to compact "y:r:s" format.
pub fn proof_to_string(proof: &SchnorrProof) -> String {
    format!("{}:{}:{}", proof.y, proof.r, proof.s)
}

/// Deserialize proof from "y:r:s" format.
pub fn proof_from_string(s: &str) -> Option<SchnorrProof> {
    let parts: Vec<&str> = s.splitn(3, ':').collect();
    if parts.len() != 3 {
        return None;
    }
    Some(SchnorrProof {
        y: parts[0].parse().ok()?,
        r: parts[1].parse().ok()?,
        s: parts[2].parse().ok()?,
    })
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Generate a ZKP proof string for a calculation.
pub fn generate_proof(expression: &str, result: &str) -> String {
    let proof = prove(expression, result);
    proof_to_string(&proof)
}

/// Verify a proof string against an expression and result.
///
/// Re-derives the witness from the expression to check that the proof
/// was generated by someone who knew the full computation.
pub fn verify_proof(expression: &str, result: &str, proof_str: &str) -> bool {
    // First verify the Schnorr proof structure
    let proof = match proof_from_string(proof_str) {
        Some(p) => p,
        None => return false,
    };

    if !verify(&proof) {
        return false;
    }

    // Also check that y matches the expected witness for this expression
    let expected_witness =
        hash_to_scalar(format!("witness:{}={}", expression, result).as_bytes());
    let expected_y = modpow(G, expected_witness, P);
    proof.y == expected_y
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prove_and_verify() {
        let proof = prove("3+5", "8");
        assert!(verify(&proof));
    }

    #[test]
    fn test_full_roundtrip() {
        let proof_str = generate_proof("10*20", "200");
        assert!(verify_proof("10*20", "200", &proof_str));
    }

    #[test]
    fn test_wrong_expression_fails() {
        let proof_str = generate_proof("3+5", "8");
        // Same result, different expression — ZKP should fail
        assert!(!verify_proof("4+4", "8", &proof_str));
    }

    #[test]
    fn test_tampered_proof_fails() {
        let proof_str = generate_proof("7-3", "4");
        // Tamper with the proof
        let tampered = format!("99999:{}", &proof_str[proof_str.find(':').unwrap() + 1..]);
        assert!(!verify_proof("7-3", "4", &tampered));
    }

    #[test]
    fn test_deterministic() {
        let p1 = generate_proof("42*1", "42");
        let p2 = generate_proof("42*1", "42");
        assert_eq!(p1, p2);
    }

    #[test]
    fn test_serialization_roundtrip() {
        let proof = prove("1+1", "2");
        let s = proof_to_string(&proof);
        let proof2 = proof_from_string(&s).unwrap();
        assert_eq!(proof.y, proof2.y);
        assert_eq!(proof.r, proof2.r);
        assert_eq!(proof.s, proof2.s);
    }
}
